### ISSUE TITLE
Issue: Reload button leads to dashboard crash

### ISSUE THREAD

**Issue by kristofzerbe** [estruyf/vscode-front-matter#664]
**Describe the bug**
 Hitting the RELOAD button in dashboard leads to a crash:

**To Reproduce**
In dashboard hit the RELOAD button in **v9.3.6172561-beta**. Close, open up again ... works again

**Expected behavior**
Reload the dashboard

**Screenshots**
![image](https://github.com/estruyf/vscode-front-matter/assets/243113/2329b57c-e08c-437d-bf4d-f2dc86db7823)

**Desktop:**
 - OS: Windows 10
 - SSG: Hexo
 - Browser: Chrome latest

**Comment by estruyf** [comment]
Can you check if anything is logged in the VSCode - Front Matter CMS output?

Is it happening on your blog? If so I'll give it a try tomorrow to see what is going on internally.

**Comment by kristofzerbe** [comment]
Of course, I forgot...

["INFO" - 18:09:41]  Receiving message from webview: refreshPages
["INFO" - 18:09:41]  Receiving message from webview: logError
["ERROR" - 18:09:41]  Event ID: e9d218614a8549438116dd9a89fc2111
Message: Cannot assign to read only property 'draft' of object '#<Object>'

Stack: 
    at Contents (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:136281:21)
    at RenderedRoute (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:116332:5)
    at Routes (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:116963:5)
    at main
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:30058:47)
    at App (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:135555:16)
    at SettingsProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:142318:29)
    at Router (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:116901:15)
    at MemoryRouter (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:116801:5)
    at RecoilRoot_INTERNAL (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:126483:3)
    at RecoilRoot (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/k.zerbe/.vscode/extensions/eliostruyf.vscode-front-matter-beta-9.3.6172561/dist/dashboardWebView.js:126639:5)
["INFO" - 18:09:42]  Sending message to dashboard: pages
["INFO" - 18:09:42]  Sending message to dashboard: searchReady
["INFO" - 18:09:42]  Sending message to dashboard: loading
["INFO" - 18:09:52]  Triggering draft status update: onDidChangeActiveTextEditor
["INFO" - 18:09:53]  Triggering draft status update: onDidChangeTextEditorSelection
["INFO" - 18:09:53]  Triggering draft status update: onDidChangeTextEditorSelection
["INFO" - 18:09:54]  Triggering draft status update: onDidChangeTextEditorSelection
["INFO" - 18:09:56]  Triggering draft status update: onDidChangeTextEditorSelection
["INFO" - 18:09:57]  Triggering draft status update: onDidChangeTextEditorSelection
["INFO" - 18:09:57]  Triggering draft status update: onDidChangeTextEditorSelection

**Comment by estruyf** [comment]
I found the issue, and it is related to the Hexo change only (it could also happen in Jekyll).

The new beta should fix it.

**Comment by kristofzerbe** [comment]
Confirm ... fixed. Thank you...
