### ISSUE TITLE
Issue: Dashboard not loading

### ISSUE THREAD

**Issue by Dekker500** [estruyf/vscode-front-matter#796]
**Describe the bug**
When the FM icon is clicked, the left-column menu appears as expected. Clicking "Open Dashboard" opens a new tab to the right, titled "Front Matter Dashboard", and the progress animation slides left-to-right without finishing.

**To Reproduce**
I have an existing HUGO project with FM installed. This used to work ~6 months ago. 
Reproducing is simply starting VS Code, clicking FM icon, then "Open Dashboard"

I have tried uninstalling the extension, restarting VS Code, then re-installing, however I get no change.
I have another different workspace that works with FM.
I suspect either FM or VS Code were updated, and something broke in the upgrade...

Extension Host has the following error shown:
```
2024-04-22 10:01:16.705 [error] TypeError: Cannot read properties of undefined (reading 'map')
	at w.<anonymous> (c:\Users\UserID\.vscode\extensions\eliostruyf.vscode-front-matter-10.1.0\dist\extension.js:1:34554)
	at w.t (c:\Users\Michael\.vscode\extensions\eliostruyf.vscode-front-matter-10.1.0\dist\vendors.a8542a5a9120a04f690d.js:2:612104)
	at w.emit (node:events:517:28)
	at w._readdirError (c:\Users\UserID\.vscode\extensions\eliostruyf.vscode-front-matter-10.1.0\dist\vendors.a8542a5a9120a04f690d.js:2:429563)
	at c:\Users\UserID\.vscode\extensions\eliostruyf.vscode-front-matter-10.1.0\dist\vendors.a8542a5a9120a04f690d.js:2:428860
	at FSReqCallback.oncomplete (node:fs:202:23)
```

**Expected behavior**
I expect the dashboard to be displayed, with published and draft posts shown.

**Screenshots**

![image](https://github.com/estruyf/vscode-front-matter/assets/5595061/74640db0-95f8-48e4-961a-e0c039ed72aa)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome
 - Version: Latest (124)

**Additional context**
FM Extension: v10.1.0

VS Code 
```
Version: 1.88.1 (system setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```
Hugo: v125.1

**Comment by estruyf** [comment]
Thanks for opening an issue. Do you have a repo which I can use to verify this?

**Comment by Dekker500** [comment]
Sorry, the project is not public.
I have attached a mildly sanitized frontmatter.json for review, if that helps.
[frontmatter copy.json](https://github.com/estruyf/vscode-front-matter/files/15065032/frontmatter.copy.json)

The two files in .frontmatter folder are empty `{}`. I could have sworn, though, that they had content last year... but that is another matter.
![image](https://github.com/estruyf/vscode-front-matter/assets/5595061/71f21917-8dd4-4b4d-a845-1778b64ce09f)

**Comment by estruyf** [comment]
I don't see anything wrong in the configuration. It had to do with the retrieval of your content, but what or why, that is something I cannot reproduce.

Do you mind sharing the project temporarily with me so I can run a debug version against it?

**Comment by Dekker500** [comment]
I just granted access through GitHub... You will need to accept access.

**Comment by estruyf** [comment]
Thanks! It loads without any issues on my main device. I will have to test it later on a Windows device to see if the problem occurs there.

**Comment by estruyf** [comment]
@Dekker500 I have tested it on my Windows 11 device, but there are no issues. Dashboard loads fine without any issue like you've mentioned.

I added an extra line to the output in the latest BETA version. Would you be able to give that a try and check if something gets logged in the Front Matter CMS output?

https://frontmatter.codes/docs/troubleshooting#looking-what-is-happening-behind-the-scenes

**Comment by Dekker500** [comment]
Sounds good, I'll check it tomorrow. 

If the message is inconclusive, I'll also try with a fresh download of the repository, in case it is something that is not synced that is causing the problem.

**Comment by estruyf** [comment]
@Dekker500 did you have time to check it out yesterday?

**Comment by estruyf** [comment]
What do you get when running the `frontMatter.diagnostics` command?

**Comment by estruyf** [comment]
@Dekker500 thanks! I hoped it wouldn't find any `mdFiles`, but it does, so it's weird that the dashboard is not showing you those articles.

I got the same output when loading your project on my Windows device.

I added some extra logging during the page parsing. In the beta version `10.2.8832943`, you should see the following during page parsing:

```
["INFO" - 14:49:29]  PagesParser::parsePages: Start
["INFO" - 14:49:29]  PagesParser::parsePages: Parsing folder Posts - 23
["INFO" - 14:49:29]  PagesParser::parsePages: End
```

I guess there is something wrong with the cache, so if you try running the `frontMatter.cache.clear` command and reopen the dashboard, you should see the above logs in the output or an error for the failed files.

**Comment by estruyf** [comment]
I've now added logging on the webview side as well; when you load the webview, you should see messages like:

```
["INFO" - 15:54:31]  DASHBOARD: loaded with view contents
["INFO" - 15:54:31]  DASHBOARD: pages loaded - 0 pages
["INFO" - 15:54:31]  DASHBOARD: Contents view loaded with 0 pages
["INFO" - 15:54:31]  DASHBOARD: settings loaded
["INFO" - 15:54:31]  DASHBOARD: pages loaded - 23 pages
["INFO" - 15:54:31]  DASHBOARD: Contents view loaded with 23 pages
```

Can you test this out in version `10.2.8833818`?
Can you record the VSCode editor when opening the dashboard?

**Comment by Dekker500** [comment]
Updated, re-started, tried launching the dashboard, and the following was in the log:

```
["INFO" - 09:58:19]  No ".frontmatter/config" config files found.
["INFO" - 09:58:19]  Trigger page update: main
["INFO" - 09:58:19]  Sending message to webview (panel&dashboard): setMode
["INFO" - 09:58:19]  PagesParser::parsePages: Start
["INFO" - 09:58:19]  PagesParser::parsePages: Parsing folder Posts - 23
["INFO" - 09:58:19]  PagesParser::parsePages: End
["INFO" - 09:58:27]  Receiving message from webview to panel: getLocalization
["INFO" - 09:58:27]  Sending request result to panel: getLocalization
["INFO" - 09:58:27]  Receiving message from webview to panel: getBranch
["INFO" - 09:58:27]  Receiving message from webview to panel: get-data
["INFO" - 09:58:27]  Receiving message from webview to panel: get-mode
["INFO" - 09:58:27]  Sending message to webview (panel&dashboard): setMode
["INFO" - 09:58:27]  Receiving message from webview to panel: getLocalization
["INFO" - 09:58:27]  Sending message to panel: settings
["INFO" - 09:58:27]  Receiving message from webview to panel: getBranch
["INFO" - 09:58:27]  Receiving message from webview to panel: is-server-started
["INFO" - 09:58:27]  Sending request result to panel: is-server-started
["INFO" - 09:58:27]  Receiving message from webview to panel: update-placeholder
["INFO" - 09:58:27]  Sending request result to panel: updatePlaceholder
["INFO" - 09:58:27]  Sending message to panel: folderInfo
["INFO" - 09:58:27]  Receiving message from webview to panel: update-metadata
["INFO" - 09:58:27]  Receiving message from webview to panel: process-media-data
["INFO" - 09:58:27]  Receiving message from webview to panel: update-metadata
["INFO" - 09:58:27]  Receiving message from webview to panel: update-metadata
["INFO" - 09:58:29]  Receiving message from webview to panel: open-dashboard
["INFO" - 09:58:29]  Receiving message from webview: getLocalization
["INFO" - 09:58:29]  Receiving message from webview: getViewType
["INFO" - 09:58:29]  Sending message to dashboard: viewData
["INFO" - 09:58:29]  Receiving message from webview: getTheme
["INFO" - 09:58:29]  Receiving message from webview: getData
["INFO" - 09:58:29]  Receiving message from webview: getMode
["INFO" - 09:58:29]  Sending message to webview (panel&dashboard): setMode
["INFO" - 09:58:29]  Receiving message from webview: logInfo
["INFO" - 09:58:29]  DASHBOARD: loaded with view contents
["INFO" - 09:58:29]  Receiving message from webview: logInfo
["INFO" - 09:58:29]  DASHBOARD: pages loaded - 0 pages
["INFO" - 09:58:29]  Sending message to dashboard: pages
["INFO" - 09:58:29]  Sending message to dashboard: pages
["INFO" - 09:58:29]  Sending message to dashboard: searchReady
["INFO" - 09:58:29]  Receiving message from webview: logInfo
["INFO" - 09:58:29]  DASHBOARD: pages loaded - 23 pages
["INFO" - 09:58:29]  Sending message to dashboard: loading - Turn off
["INFO" - 09:58:34]  Trigger page update: onDidChangeActiveTextEditor
["INFO" - 09:58:35]  Sending message to panel: metadata
["INFO" - 09:58:35]  Receiving message from webview to panel: getBranch
["INFO" - 09:58:35]  Receiving message from webview to panel: is-server-started
["INFO" - 09:58:35]  Sending request result to panel: is-server-started
```

**Comment by estruyf** [comment]
It seems to come from your settings 🤔.

In this reply: https://github.com/estruyf/vscode-front-matter/issues/796#issuecomment-2077076982

Did you remove the configuration on purpose? Or was it just not present?

**Comment by Dekker500** [comment]
Oh, I removed it on purpose, the JSON was already attached above, but here it is again, complete:

# Project name

D2VO

# Folders

- Posts: "c:/Hugo/D2VO/content/posts"

# Workspace folder

c:\Hugo\D2VO

# Total files

Total files found: 16828

# Folders to search files

- Project start length: 13 | Search in: "content\posts\**\*.*" | mdFiles: 23 | mdxFiles: 0 | markdownFiles: 0

# Complete frontmatter.json config

```json
{
  "$schema": "https://frontmatter.codes/frontmatter.schema.json",
  "frontMatter.taxonomy.contentTypes": [
    {
      "name": "default",
      "pageBundle": true,
      "previewPath": null,
      "defaultFileName": "index",
      "template": "[[workspace]]/archetypes/article.md",
      "fields": [
        {
          "title": "Title",
          "name": "title",
          "type": "string"
        },
        {
          "title": "Slug",
          "name": "slug",
          "type": "slug",
          "editable": true,
          "default": "{{slug}}"
        },
        {
          "title": "Description",
          "name": "description",
          "type": "string"
        },
        {
          "title": "Publishing date",
          "name": "date",
          "type": "datetime",
          "default": "{{now}}",
          "isPublishDate": true
        },
        {
          "title": "Last modified date",
          "name": "lastmod",
          "type": "datetime",
          "isModifiedDate": true
        },
        {
          "title": "Featured image",
          "name": "featuredImage",
          "type": "image"
        },
        {
          "title": "Is in draft",
          "name": "draft",
          "type": "draft",
          "default": true
        },
        {
          "title": "Tags",
          "name": "tags",
          "type": "tags"
        },
        {
          "title": "Categories",
          "name": "categories",
          "type": "categories"
        },
        {
          "title": "Author",
          "name": "author",
          "type": "string",
          "default": "my_name"
        },
        {
          "title": "Author image",
          "name": "authorimage",
          "type": "image",
          "default": "/images/global/author/my_pic.png"
        },
        {
          "title": "sitemap",
          "name": "sitemap",
          "type": "fields",
          "fields": [
            {
              "title": "changefreq",
              "name": "changefreq",
              "type": "string",
              "default": "monthly"
            },
            {
              "title": "priority",
              "name": "priority",
              "type": "number",
              "default": "0.8"
            }
          ]
        }
      ]
    }
  ],
  "frontMatter.framework.id": "hugo",
  "frontMatter.content.publicFolder": "static",
  "frontMatter.preview.host": "http://localhost:1313",
  "frontMatter.site.baseURL": "https://www.my_site.com",
  "frontMatter.sponsors.ai.enabled": true,
  "frontMatter.taxonomy.alignFilename": false,
  "frontMatter.taxonomy.frontMatterType": "YAML",
  "frontMatter.taxonomy.slugPrefix": "",
  "frontMatter.content.pageFolders": [
    {
      "title": "Posts",
      "path": "[[workspace]]/content/posts",
      "previewPath": "'/posts'",
      "contentTypes": [
        "default"
      ]
    }
  ],
  "frontMatter.taxonomy.tags": [],
  "frontMatter.taxonomy.categories": []
}
```

**Comment by estruyf** [comment]
Ah, ok, I just needed to know if you removed it, since the dashboard doesn't get your settings for some reason. I'm looking for a clue there :-).

**Comment by Dekker500** [comment]
No problem. My replies might be "slow" as the day job is keeping me busy though :)

I still haven't had the chance/time to pull the repo into a fresh location and trying there... That might fix it for me, but thought I'd see if there was an actual "fix" that might help others who get into the same situation.

**Comment by estruyf** [comment]
> I still haven't had the chance/time to pull the repo into a fresh location and trying there... That might fix it for me, but thought I'd see if there was an actual "fix" that might help others who get into the same situation.

I would also like to understand what is actually going on, as this is the first time it occurred. 

New version `10.2.8834387` includes some extra logging for settings retrieval.

**Comment by Dekker500** [comment]
Update (v10.2.8834387), restart, attempt to open dashboard (using left-hand bar's "open dashboard"), still no response with the following log:

```
["INFO" - 10:33:01]  No ".frontmatter/config" config files found.
["INFO" - 10:33:01]  Project config path: c:\Hugo\D2VO\frontmatter.json
["INFO" - 10:33:01]  Trigger page update: main
["INFO" - 10:33:01]  Sending message to webview (panel&dashboard): setMode
["INFO" - 10:33:01]  Getting dashboard settings
["INFO" - 10:33:01]  PagesParser::parsePages: Start
["INFO" - 10:33:01]  PagesParser::parsePages: Parsing folder Posts - 23
["INFO" - 10:33:01]  PagesParser::parsePages: End
["INFO" - 10:33:14]  Receiving message from webview to panel: getLocalization
["INFO" - 10:33:14]  Sending request result to panel: getLocalization
["INFO" - 10:33:14]  Receiving message from webview to panel: getBranch
["INFO" - 10:33:14]  Receiving message from webview to panel: get-data
["INFO" - 10:33:14]  Getting panel settings
["INFO" - 10:33:14]  Receiving message from webview to panel: get-mode
["INFO" - 10:33:14]  Sending message to webview (panel&dashboard): setMode
["INFO" - 10:33:14]  Receiving message from webview to panel: getLocalization
["INFO" - 10:33:14]  Sending message to panel: settings
["INFO" - 10:33:14]  Receiving message from webview to panel: getBranch
["INFO" - 10:33:14]  Receiving message from webview to panel: is-server-started
["INFO" - 10:33:14]  Sending request result to panel: is-server-started
["INFO" - 10:33:14]  Receiving message from webview to panel: update-placeholder
["INFO" - 10:33:14]  Sending request result to panel: updatePlaceholder
["INFO" - 10:33:14]  Sending message to panel: folderInfo
["INFO" - 10:33:14]  Receiving message from webview to panel: update-metadata
["INFO" - 10:33:14]  Receiving message from webview to panel: process-media-data
["INFO" - 10:33:14]  Receiving message from webview to panel: update-metadata
["INFO" - 10:33:14]  Receiving message from webview to panel: update-metadata
["INFO" - 10:33:16]  Receiving message from webview to panel: open-dashboard
["INFO" - 10:33:17]  Receiving message from webview: getLocalization
["INFO" - 10:33:17]  Receiving message from webview: getViewType
["INFO" - 10:33:17]  Sending message to dashboard: viewData
["INFO" - 10:33:17]  Receiving message from webview: getTheme
["INFO" - 10:33:17]  Receiving message from webview: getData
["INFO" - 10:33:17]  Getting dashboard settings
["INFO" - 10:33:17]  Receiving message from webview: getMode
["INFO" - 10:33:17]  Sending message to webview (panel&dashboard): setMode
["INFO" - 10:33:17]  Receiving message from webview: logInfo
["INFO" - 10:33:17]  DASHBOARD: loaded with view contents
["INFO" - 10:33:17]  Receiving message from webview: logInfo
["INFO" - 10:33:17]  DASHBOARD: pages loaded - 0 pages
["INFO" - 10:33:17]  Sending message to dashboard: pages
["INFO" - 10:33:17]  Sending message to dashboard: pages
["INFO" - 10:33:17]  Sending message to dashboard: searchReady
["INFO" - 10:33:17]  Receiving message from webview: logInfo
["INFO" - 10:33:17]  DASHBOARD: pages loaded - 23 pages
["INFO" - 10:33:17]  Sending message to dashboard: loading - Turn off
["INFO" - 10:33:23]  Trigger page update: onDidChangeActiveTextEditor

```

No change in "diagnostics output" either.

**Comment by estruyf** [comment]
More logging added, I hope we're getting closer to where the problem is coming from. Version `10.2.8835247`

**Comment by estruyf** [comment]
Ok, I can now see where the setting retrieval is "hanging". More logging in the folder retrieval functions. Version `10.2.8835572`

**Comment by Dekker500** [comment]
Repeating testing with v10.2.8835572

After restarting VS Code, but before attempting to launch the dashboard, the following was in the log:
```
["INFO" - 11:54:33] VSCODE | No ".frontmatter/config" config files found.
["INFO" - 11:54:33] VSCODE | Project config path: c:\Hugo\D2VO\frontmatter.json
["INFO" - 11:54:33] VSCODE | Trigger page update: main
["INFO" - 11:54:33] VSCODE | Sending message to webview (panel&dashboard): setMode
["INFO" - 11:54:33] VSCODE | DashboardSettings:getSettings:start
["INFO" - 11:54:33] VSCODE | PagesParser:parsePages:start
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:start - c:\Hugo\D2VO\content\posts\**\*.md
["INFO" - 11:54:33] VSCODE | GitListener:getSettings:start
["INFO" - 11:54:33] VSCODE | GitListener:getSettings:end:disabled
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:start:1
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:end - 23
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:start - c:\Hugo\D2VO\content\posts\**\*.markdown
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:end:1
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:start:2
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:end:2
["INFO" - 11:54:33] VSCODE | Folders:getContentFolders:start
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:start - c:\Hugo\D2VO\**\*.md
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:end - 0
["ERROR" - 11:54:33] VSCODE | Folders:findFolders:error - EPERM: operation not permitted, scandir 'c:\Hugo\D2VO\assets\images\global\audio interface.svg'
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:end - 0
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:start - c:\Hugo\D2VO\**\*.markdown
["ERROR" - 11:54:33] VSCODE | Folders:findFolders:error - EPERM: operation not permitted, scandir 'c:\Hugo\D2VO\assets\images\global\audio interface.svg'
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:end - 0
["INFO" - 11:54:33] VSCODE | Folders:getContentFolders:end
["INFO" - 11:54:33] VSCODE | DashboardSettings:getDataFiles:start
["INFO" - 11:54:33] VSCODE | DashboardSettings:getDataFiles:end
["INFO" - 11:54:33] VSCODE | DashboardSettings:getSettings:end
["INFO" - 11:54:33] VSCODE | PagesParser::parsePages: Parsing folder Posts - 23
["INFO" - 11:54:33] VSCODE | PagesParser:parsePages:end
["INFO" - 11:54:42] VSCODE | Trigger page update: onDidChangeActiveTextEditor

```

After attempting to launch the dashboard, the following is the complete log:
```
["INFO" - 11:54:33] VSCODE | No ".frontmatter/config" config files found.
["INFO" - 11:54:33] VSCODE | Project config path: c:\Hugo\D2VO\frontmatter.json
["INFO" - 11:54:33] VSCODE | Trigger page update: main
["INFO" - 11:54:33] VSCODE | Sending message to webview (panel&dashboard): setMode
["INFO" - 11:54:33] VSCODE | DashboardSettings:getSettings:start
["INFO" - 11:54:33] VSCODE | PagesParser:parsePages:start
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:start - c:\Hugo\D2VO\content\posts\**\*.md
["INFO" - 11:54:33] VSCODE | GitListener:getSettings:start
["INFO" - 11:54:33] VSCODE | GitListener:getSettings:end:disabled
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:start:1
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:end - 23
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:start - c:\Hugo\D2VO\content\posts\**\*.markdown
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:end:1
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:start:2
["INFO" - 11:54:33] VSCODE | TaxonomyHelper:get:end:2
["INFO" - 11:54:33] VSCODE | Folders:getContentFolders:start
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:start - c:\Hugo\D2VO\**\*.md
["VERBOSE" - 11:54:33] VSCODE | Folders:findFiles:end - 0
["ERROR" - 11:54:33] VSCODE | Folders:findFolders:error - EPERM: operation not permitted, scandir 'c:\Hugo\D2VO\assets\images\global\audio interface.svg'
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:end - 0
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:start - c:\Hugo\D2VO\**\*.markdown
["ERROR" - 11:54:33] VSCODE | Folders:findFolders:error - EPERM: operation not permitted, scandir 'c:\Hugo\D2VO\assets\images\global\audio interface.svg'
["VERBOSE" - 11:54:33] VSCODE | Folders:findFolders:end - 0
["INFO" - 11:54:33] VSCODE | Folders:getContentFolders:end
["INFO" - 11:54:33] VSCODE | DashboardSettings:getDataFiles:start
["INFO" - 11:54:33] VSCODE | DashboardSettings:getDataFiles:end
["INFO" - 11:54:33] VSCODE | DashboardSettings:getSettings:end
["INFO" - 11:54:33] VSCODE | PagesParser::parsePages: Parsing folder Posts - 23
["INFO" - 11:54:33] VSCODE | PagesParser:parsePages:end
["INFO" - 11:54:42] VSCODE | Trigger page update: onDidChangeActiveTextEditor
["INFO" - 11:55:47] VSCODE | Receiving message from panel: getLocalization
["INFO" - 11:55:47] VSCODE | Sending request result to panel: getLocalization
["INFO" - 11:55:47] VSCODE | Receiving message from panel: getBranch
["INFO" - 11:55:47] VSCODE | Receiving message from panel: get-data
["VERBOSE" - 11:55:47] VSCODE | Folders:findFiles:start - c:\Hugo\D2VO\content\posts\**\*.md
["INFO" - 11:55:47] VSCODE | Getting panel settings
["INFO" - 11:55:47] VSCODE | GitListener:getSettings:start
["INFO" - 11:55:47] VSCODE | GitListener:getSettings:end:disabled
["INFO" - 11:55:47] VSCODE | TaxonomyHelper:get:start:1
["INFO" - 11:55:47] VSCODE | TaxonomyHelper:get:end:1
["INFO" - 11:55:47] VSCODE | TaxonomyHelper:get:start:2
["INFO" - 11:55:47] VSCODE | TaxonomyHelper:get:end:2
["INFO" - 11:55:47] VSCODE | Receiving message from panel: get-mode
["INFO" - 11:55:47] VSCODE | Sending message to webview (panel&dashboard): setMode
["INFO" - 11:55:47] VSCODE | Receiving message from panel: getLocalization
["INFO" - 11:55:47] VSCODE | Sending message to panel: settings
["VERBOSE" - 11:55:47] VSCODE | Folders:findFiles:end - 23
["VERBOSE" - 11:55:47] VSCODE | Folders:findFiles:start - c:\Hugo\D2VO\content\posts\**\*.markdown
["VERBOSE" - 11:55:47] VSCODE | Folders:findFiles:end - 0
["INFO" - 11:55:47] VSCODE | Receiving message from panel: getBranch
["INFO" - 11:55:47] VSCODE | Receiving message from panel: is-server-started
["INFO" - 11:55:47] VSCODE | Sending request result to panel: is-server-started
["INFO" - 11:55:47] VSCODE | Receiving message from panel: update-placeholder
["INFO" - 11:55:47] VSCODE | Sending request result to panel: updatePlaceholder
["INFO" - 11:55:47] VSCODE | Receiving message from panel: update-metadata
["INFO" - 11:55:47] VSCODE | Sending message to panel: metadata
["INFO" - 11:55:47] VSCODE | Receiving message from panel: process-media-data
["INFO" - 11:55:47] VSCODE | Sending request result to panel: process-media-data
["INFO" - 11:55:47] VSCODE | Sending message to panel: folderInfo
["INFO" - 11:55:47] VSCODE | Receiving message from panel: update-metadata
["INFO" - 11:55:47] VSCODE | Sending message to panel: metadata
["INFO" - 11:55:47] VSCODE | Receiving message from panel: getBranch
["INFO" - 11:55:47] VSCODE | Receiving message from panel: is-server-started
["INFO" - 11:55:47] VSCODE | Sending request result to panel: is-server-started
["INFO" - 11:55:49] VSCODE | Receiving message from panel: open-dashboard
["INFO" - 11:55:49] VSCODE | Trigger page update: onDidChangeActiveTextEditor
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getLocalization
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getViewType
["INFO" - 11:55:49] VSCODE | Sending message to dashboard: viewData
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getTheme
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getData
["INFO" - 11:55:49] VSCODE | SettingsListener:getSettings:start - clear: false
["INFO" - 11:55:49] VSCODE | SettingsListener:getSettings:end - setting keys: 31
["INFO" - 11:55:49] VSCODE | Sending message to dashboard: settings
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getMode
["INFO" - 11:55:49] VSCODE | Sending message to webview (panel&dashboard): setMode
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Loaded with view contents
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Pages loaded - 0 pages
["INFO" - 11:55:49] VSCODE | Sending message to dashboard: pages
["INFO" - 11:55:49] VSCODE | Sending message to dashboard: pages
["INFO" - 11:55:49] VSCODE | Sending message to dashboard: searchReady
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getState
["INFO" - 11:55:49] VSCODE | Sending message to dashboard: loading - Turn off
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getState
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Contents view loaded with 0 pages
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: sendTelemetry
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Settings loaded
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Pages loaded - 0 pages
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getState
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getState
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getContentLocales
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Settings loaded
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Pages loaded - 23 pages
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getPinnedItems
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getState
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: getContentLocales
["INFO" - 11:55:49] VSCODE | Receiving message from dashboard: logInfo
["INFO" - 11:55:49] DASHBOARD | Contents view loaded with 23 pages
["INFO" - 11:55:50] VSCODE | Sending message to panel: metadata
["INFO" - 11:55:50] VSCODE | Receiving message from panel: getBranch
["INFO" - 11:55:50] VSCODE | Receiving message from panel: is-server-started
["INFO" - 11:55:50] VSCODE | Sending request result to panel: is-server-started
["INFO" - 11:55:53] VSCODE | Trigger page update: onDidChangeActiveTextEditor
["INFO" - 11:55:53] VSCODE | Receiving message from panel: getBranch
["INFO" - 11:55:53] VSCODE | Receiving message from panel: is-server-started
["INFO" - 11:55:53] VSCODE | Sending request result to panel: is-server-started

```

### NOTE: THE DASHBOARD NOW APPEARS!!!

Furthermore, it appears that a "new" file was created: pinnedItemsDB.json. Or should I say, it had no contents before.
![image](https://github.com/estruyf/vscode-front-matter/assets/5595061/e74e034c-bb54-4cce-adb2-3aceaf6f5df5)

with the following content:
```
---
draft: true
slug: ""
---
{}
'''


I even re-started VS Code, and it still "works". Don't know what you did on the back-end, but it appears to have resolved the issue.

**Comment by estruyf** [comment]
The `pinnedItemsDB.json` file is indeed a new file that was introduced in version `9.3.0`. The file will be empty when you have no pinned content, so this is just fine.

I added extra logging in the folder/file retrieval, and it seems that there was an issue: `EPERM: operation not permitted, scandir 'c:\Hugo\D2VO\assets\images\global\audio interface.svg'`. That seemed to be the issue, but now I need to see why it thinks the SVG is a folder.

**Comment by estruyf** [comment]
Thanks @Dekker500 for testing all of the released beta versions 🙏

**Comment by Dekker500** [comment]
Interesting... That file is indeed supposed to be an SVG, but when I just tried to view it, VS Code gave me the following error:

![image](https://github.com/estruyf/vscode-front-matter/assets/5595061/bd480ee7-1c51-49fb-bf1c-aa2b516b20e6)

So FrontMatter should handle the exception better, however I DEFINITELY need to figure out what is going on with that image! It is not "caused" by FM, but FM just didn't know how to react.

I'll update when I know what's going on on my side...

**Comment by estruyf** [comment]
Indeed, now FM skips the file and returns the error in the output.

Let me know your finding around the file.
